const crypto = require('crypto');

const WORDS = [
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball',
  'band', 'bank', 'base', 'bath', 'bean', 'bear', 'beat', 'been', 'beer', 'bell',
  'belt', 'best', 'bill', 'bird', 'bite', 'blow', 'blue', 'blur', 'boat', 'body',
  'bolt', 'bomb', 'bond', 'bone', 'book', 'boom', 'boot', 'born', 'boss', 'both',
  'bowl', 'bulk', 'burn', 'bush', 'busy', 'buzz', 'cafe', 'cage', 'cake', 'call',
  'calm', 'came', 'camp', 'card', 'care', 'cart', 'case', 'cash', 'cast', 'cave',
  'cell', 'chat', 'chef', 'chin', 'chip', 'chop', 'cite', 'city', 'clad', 'clam',
  'clan', 'clap', 'claw', 'clay', 'clip', 'clock', 'clone', 'close', 'cloud', 'club',
  'clue', 'coal', 'coat', 'code', 'coil', 'coin', 'cold', 'cole', 'colt', 'come',
  'cook', 'cool', 'cope', 'copy', 'cord', 'core', 'corn', 'cost', 'cozy', 'crab',
  'crew', 'crop', 'crow', 'cube', 'cult', 'cure', 'curl', 'cute', 'dale', 'dame',
  'damp', 'dare', 'dark', 'dart', 'dash', 'data', 'dawn', 'deal', 'dear', 'debt',
  'deck', 'deed', 'deep', 'deer', 'demo', 'deny', 'desk', 'dial', 'dice', 'diet',
  'dirt', 'disc', 'dish', 'disk', 'dock', 'does', 'dome', 'done', 'doom', 'door',
  'dose', 'dove', 'down', 'drag', 'draw', 'drip', 'drop', 'drum', 'dual', 'duck',
  'dude', 'duel', 'duke', 'dull', 'dumb', 'dump', 'dune', 'dusk', 'dust', 'duty',
  'each', 'earl', 'earn', 'ease', 'east', 'easy', 'edge', 'edit', 'else', 'epic',
  'euro', 'even', 'ever', 'evil', 'exam', 'exit', 'expo', 'face', 'fact', 'fade',
  'fail', 'fair', 'fake', 'fall', 'fame', 'fang', 'fare', 'farm', 'fast', 'fate',
  'fawn', 'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt', 'file', 'fill',
  'film', 'find', 'fine', 'fire', 'firm', 'fish', 'fist', 'flag', 'flame', 'flap',
  'flat', 'flaw', 'fled', 'flew', 'flex', 'flip', 'flit', 'flock', 'flood', 'flow',
  'foam', 'foil', 'fold', 'folk', 'fond', 'font', 'food', 'fool', 'foot', 'ford',
  'fork', 'form', 'fort', 'foul', 'four', 'fowl', 'free', 'frog', 'from', 'fuel',
  'full', 'fund', 'fury', 'fuse', 'fuss', 'gain', 'gale', 'game', 'gang', 'gate',
  'gave', 'gaze', 'gear', 'gene', 'gift', 'gild', 'girl', 'give', 'glad', 'glen',
  'glow', 'glue', 'goat', 'goes', 'gold', 'golf', 'gone', 'good', 'grab', 'gram',
  'gray', 'grew', 'grid', 'grim', 'grin', 'grip', 'grow', 'gulf', 'guru', 'gust',
  'hack', 'hail', 'hair', 'half', 'hall', 'halt', 'hand', 'hang', 'hare', 'harm',
  'harp', 'hate', 'haul', 'have', 'hawk', 'haze', 'head', 'heal', 'heap', 'hear',
  'heat', 'held', 'helm', 'help', 'herb', 'herd', 'here', 'hero', 'hide', 'high',
  'hike', 'hill', 'hint', 'hire', 'hold', 'hole', 'holy', 'home', 'hood', 'hook',
  'hope', 'horn', 'host', 'hour', 'huge', 'hull', 'hung', 'hunt', 'hurt', 'hymn',
  'icon', 'idea', 'inch', 'info', 'iron', 'isle', 'item', 'jack', 'jade', 'jail',
  'jake', 'jane', 'jazz', 'jean', 'jeep', 'jerk', 'jest', 'jewel', 'jinx', 'join',
  'joke', 'jolt', 'jump', 'june', 'jury', 'just', 'keen', 'keep', 'kelp', 'kept',
  'kick', 'kill', 'kind', 'king', 'kiss', 'kite', 'knee', 'knew', 'knit', 'knob',
  'knot', 'know', 'lace', 'lack', 'lady', 'laid', 'lake', 'lamb', 'lame', 'lamp',
  'land', 'lane', 'lard', 'lark', 'last', 'late', 'lawn', 'lazy', 'lead', 'leaf',
  'leak', 'lean', 'leap', 'left', 'lend', 'lens', 'less', 'liar', 'lick', 'life',
  'lift', 'like', 'limb', 'lime', 'limp', 'line', 'link', 'lion', 'list', 'live',
  'load', 'loaf', 'loan', 'lock', 'loft', 'logo', 'lone', 'long', 'look', 'loop',
  'lord', 'lore', 'lose', 'loss', 'lost', 'loud', 'love', 'luck', 'lull', 'lump',
  'lung', 'lure', 'lurk', 'lush', 'lust', 'made', 'mail', 'main', 'make', 'male',
  'mall', 'malt', 'mane', 'many', 'mare', 'mark', 'mars', 'mask', 'mass', 'mast',
  'mate', 'maze', 'mead', 'meal', 'mean', 'meat', 'meet', 'melt', 'memo', 'mend',
  'menu', 'mere', 'mesh', 'mess', 'mice', 'mild', 'milk', 'mill', 'mime', 'mind',
  'mine', 'mint', 'miss', 'mist', 'moan', 'moat', 'mock', 'mode', 'mold', 'mole',
  'monk', 'mood', 'moon', 'moor', 'more', 'moss', 'most', 'moth', 'move', 'much',
  'mule', 'muse', 'mush', 'must', 'mute', 'myth', 'nail', 'name', 'navy', 'near',
  'neat', 'neck', 'need', 'nest', 'news', 'next', 'nice', 'nine', 'node', 'none',
  'noon', 'norm', 'nose', 'note', 'noun', 'nude', 'null', 'numb', 'oath', 'obey',
  'odds', 'omen', 'omit', 'once', 'only', 'onto', 'opal', 'open', 'oral', 'orca',
  'oval', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pail', 'pain', 'pair',
  'pale', 'palm', 'pane', 'pang', 'park', 'part', 'pass', 'past', 'path', 'pave',
  'pawn', 'peak', 'pear', 'peel', 'peer', 'pelt', 'pest', 'pick', 'pier', 'pike',
  'pile', 'pine', 'pink', 'pipe', 'plan', 'play', 'plea', 'plod', 'plot', 'plow',
  'ploy', 'plug', 'plum', 'plus', 'poem', 'poet', 'poke', 'pole', 'poll', 'polo',
  'pond', 'pony', 'pool', 'pope', 'pore', 'pork', 'port', 'pose', 'post', 'pour',
  'pray', 'prey', 'prop', 'pull', 'pulp', 'pump', 'punk', 'pure', 'push', 'quit',
  'quiz', 'race', 'rack', 'raft', 'rage', 'raid', 'rail', 'rain', 'rake', 'ramp',
  'rang', 'rank', 'rare', 'rash', 'rate', 'rave', 'rays', 'read', 'real', 'reap',
  'rear', 'reed', 'reef', 'reel', 'rely', 'rent', 'rest', 'rice', 'rich', 'ride',
  'rift', 'ring', 'riot', 'rise', 'risk', 'road', 'roam', 'roar', 'robe', 'rock',
  'rode', 'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'ruin', 'rule',
  'rush', 'rust', 'safe', 'sage', 'said', 'sail', 'sake', 'sale', 'salt', 'same',
  'sand', 'sang', 'sank', 'save', 'seal', 'seam', 'seat', 'seed', 'seek', 'self',
  'sell', 'send', 'sent', 'shed', 'ship', 'shop', 'shot', 'show', 'shut', 'sick',
  'side', 'sift', 'sigh', 'sign', 'silk', 'sing', 'sink', 'site', 'size', 'skip',
  'slab', 'slam', 'slap', 'slat', 'sled', 'slew', 'slid', 'slim', 'slip', 'slit',
  'slot', 'slow', 'slug', 'snap', 'snip', 'snow', 'snug', 'soak', 'soap', 'soar',
  'sock', 'soda', 'sofa', 'soft', 'soil', 'sold', 'sole', 'some', 'song', 'soon',
  'sore', 'sort', 'soul', 'sour', 'span', 'spar', 'spec', 'sped', 'spin', 'spit',
  'spot', 'spur', 'star', 'stay', 'stem', 'step', 'stew', 'stir', 'stop', 'stow',
  'stub', 'stud', 'such', 'suit', 'sulk', 'sung', 'sunk', 'sure', 'surf', 'swap',
  'swim', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'taps',
  'tart', 'task', 'taxi', 'teak', 'teal', 'team', 'tear', 'tell', 'tend', 'tent',
  'term', 'test', 'text', 'than', 'that', 'them', 'then', 'they', 'thin', 'this',
  'tick', 'tide', 'tidy', 'tile', 'till', 'tilt', 'time', 'tiny', 'tire', 'toad',
  'toil', 'told', 'toll', 'tomb', 'tone', 'took', 'tool', 'tops', 'tore', 'torn',
  'toss', 'tour', 'town', 'trap', 'tray', 'tree', 'trek', 'trim', 'trio', 'trip',
  'trot', 'true', 'tube', 'tuck', 'tuna', 'tune', 'turf', 'turn', 'twin', 'type',
  'unit', 'upon', 'urge', 'used', 'user', 'vain', 'vale', 'van', 'vane', 'vary',
  'vast', 'veil', 'vein', 'vent', 'verb', 'very', 'vest', 'veto', 'view', 'vine',
  'visa', 'void', 'volt', 'vote', 'wade', 'wage', 'wait', 'wake', 'walk', 'wall',
  'wand', 'want', 'ward', 'warm', 'warn', 'warp', 'wart', 'wash', 'wave', 'wavy',
  'waxy', 'weak', 'wear', 'weed', 'week', 'weld', 'well', 'went', 'were', 'west',
  'what', 'when', 'whim', 'whip', 'whom', 'wick', 'wide', 'wife', 'wild', 'will',
  'wilt', 'wily', 'wind', 'wine', 'wing', 'wink', 'wipe', 'wire', 'wise', 'wish',
  'wisp', 'with', 'woke', 'wolf', 'wood', 'wool', 'word', 'wore', 'work', 'worm',
  'worn', 'wrap', 'wren', 'yard', 'yarn', 'year', 'yell', 'yoga', 'yolk', 'your',
  'zeal', 'zero', 'zinc', 'zone', 'zoom',
];

function generateCode() {
  const w1 = WORDS[crypto.randomInt(WORDS.length)];
  const w2 = WORDS[crypto.randomInt(WORDS.length)];
  const digits = crypto.randomInt(10000).toString().padStart(4, '0');
  return `${w1}-${w2}-${digits}`;
}

module.exports = { WORDS, generateCode };
